language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

script:
  - python test_app.py
deploy:
  provider: heroku
  api_key:
    secure: 26edc6db-b707-4520-84f3-85dee23e3fcb
  app:  featurerequest
